on: [push]

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker build
      run: |
        docker build . -t sennegeerts/pe-frontend:latest
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Docker push
      run: |
        docker push sennegeerts/pe-frontend
    - name: Webhook
      uses: jasongitmail/fast-webhook@v1
      with:
          url: ${{ secrets.WEBHOOK_URL }}
          json: '{}'
